linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/np-guard
  goconst:
    min-len: 6
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - unnamedResult
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/np-guard
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
        ignored-numbers: 0,1,2,3
        ignored-functions: strings.SplitN

  govet:
    check-shadowing: true
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  gosec:
    # Exclude generated files
    exclude-generated: true
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
        severity: warning
      - name: add-constant
        severity: warning
        arguments:
          - maxLitCount: "1"
            allowStrs: '"",".","-","/","\n","\n\n","\t","error","true","false"'
            allowInts: "0,1,2,404"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    # - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - revive

  # don't enable:
  # - asciicheck
  # - depguard
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - misspell
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl
issues:
  exclude-rules:
    - path: _test\.go
      linters:
       - dupl
       - revive
       - goconst
       - funlen
    - path: _test\.go
      linters:
      - staticcheck
      text: "SA1019"
    - linters:
      - lll
      source: "^// .kubebuilder:"


run:
  timeout: 5m
